version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.1.1
    container_name: master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.1.1
    container_name: worker-a
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
  spark-worker-b:
    image: cluster-apache-spark:3.1.1
    container_name: worker-b
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
  
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=123456789
    ports:
        - "9001:9001"
        - "9000:9000"
    volumes:
        - ./S3/data:/data
    command: server /data --console-address ":9001" 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 30s
        retries: 3
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    image: hive-metastore:3.0.0
    container_name: hive-metastore
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
    - 9083:9083
    depends_on:
      - mariadb
  
  presto:
    image: presto:0.272.1
    container_name: presto
    volumes:
      - ./presto-config:/opt/presto/etc
    ports:
    - 8000:8080
